export const projectsData = [
  {
    id: 1,
    title: "Scada Implementation",
    description: "SCADA implementation for boiler and turbine plant",
    startdate: "2025-01-15T10:30:00",
    enddate: "2025-04-15T10:30:00",
    category: "SCADA Development",
    cost: "1.5 Cr",
    status: "Completed",
    priority: "High",
    duraioton: "1 year",
    client: "Haldiram",
    location: "Noida",
    service: "Service Not Included",
  },
  {
    id: 2,
    title: "Energy Monitoring Dashboard",
    description:
      "Web-based dashboard for real-time energy consumption tracking",
    startdate: "2024-06-01T09:00:00",
    enddate: "2024-12-01T18:00:00",
    category: "Dashboard UI/UX",
    cost: "80 Lakh",
    status: "In Progress",
    priority: "Medium",
    duraioton: "6 months",
    client: "Bikaji Foods",
    location: "Bikaner",
    service: "Service Included",
  },
  {
    id: 3,
    title: "Automation Upgrade",
    description: "PLC and HMI upgrade for packaging line",
    startdate: "2023-09-10T08:00:00",
    enddate: "2024-03-10T17:00:00",
    category: "Industrial Automation",
    cost: "60 Lakh",
    status: "Completed",
    priority: "High",
    duraioton: "6 months",
    client: "Nestle",
    location: "Manesar",
    service: "Service Included",
  },
  {
    id: 4,
    title: "MES Integration",
    description: "Integrating MES with SAP system for data flow",
    startdate: "2023-01-01T10:00:00",
    enddate: "2024-01-01T17:30:00",
    category: "System Integration",
    cost: "2 Cr",
    status: "Completed",
    priority: "High",
    duraioton: "1 year",
    client: "Parle",
    location: "Mumbai",
    service: "Service Not Included",
  },
  {
    id: 5,
    title: "Water Treatment Automation",
    description: "Control and monitoring system for WTP",
    startdate: "2024-02-15T08:00:00",
    enddate: "2024-08-15T16:00:00",
    category: "Water Automation",
    cost: "75 Lakh",
    status: "In Progress",
    priority: "Medium",
    duraioton: "6 months",
    client: "ITC Limited",
    location: "Kolkata",
    service: "Service Included",
  },
  {
    id: 6,
    title: "HVAC SCADA System",
    description: "SCADA system for HVAC monitoring and control",
    startdate: "2023-11-20T09:00:00",
    enddate: "2024-05-20T17:00:00",
    category: "SCADA Development",
    cost: "90 Lakh",
    status: "Completed",
    priority: "Low",
    duraioton: "6 months",
    client: "Amul",
    location: "Ahmedabad",
    service: "Service Not Included",
  },
  {
    id: 7,
    title: "Data Logger Development",
    description: "Custom data logging system for temperature sensors",
    startdate: "2024-01-10T09:30:00",
    enddate: "2024-04-10T17:30:00",
    category: "IoT Development",
    cost: "30 Lakh",
    status: "Completed",
    priority: "Medium",
    duraioton: "3 months",
    client: "Mother Dairy",
    location: "Delhi",
    service: "Service Included",
  },
  {
    id: 8,
    title: "Cold Storage Automation",
    description: "Automated controls for cold storage management",
    startdate: "2024-05-01T10:00:00",
    enddate: "2024-10-01T18:00:00",
    category: "Refrigeration Automation",
    cost: "1.2 Cr",
    status: "In Progress",
    priority: "High",
    duraioton: "5 months",
    client: "Reliance Fresh",
    location: "Pune",
    service: "Service Included",
  },
  {
    id: 9,
    title: "Smart Lighting System",
    description: "Smart lighting automation for office floors",
    startdate: "2023-07-01T09:00:00",
    enddate: "2023-12-01T18:00:00",
    category: "Building Automation",
    cost: "45 Lakh",
    status: "Completed",
    priority: "Low",
    duraioton: "5 months",
    client: "Infosys",
    location: "Bangalore",
    service: "Service Not Included",
  },
  {
    id: 10,
    title: "Remote Pump Monitoring",
    description: "IoT-based solution to remotely monitor pump stations",
    startdate: "2024-03-01T10:30:00",
    enddate: "2024-08-01T17:30:00",
    category: "IoT Development",
    cost: "55 Lakh",
    status: "In Progress",
    priority: "Medium",
    duraioton: "5 months",
    client: "L&T",
    location: "Chennai",
    service: "Service Included",
  },
];
